#version: '3'
services:
  demo-app:
    build: .
    volumes:
#      - .dockervenv:/src/venv
      - .:/src
    ports:
        - "8000:8000" # 호스트의 8000 포트를 컨테이너의 8000 포트로 매핑
    environment:
      - WATCHFILES_FORCE_POLLING=True # 환경에 따라 파일 변경 감지 방식을 폴링으로 설정